const countriesData = [
  { name: "Afghanistan", callingCode: "93", code: "AF", flag: "🇦🇫", language: 'Ingles' },
  { name: "Åland Islands", callingCode: "358", code: "AX", flag: "🇦🇽", language: 'Ingles' },
  { name: "Albania", callingCode: "355", code: "AL", flag: "🇦🇱", language: 'Ingles' },
  { name: "Algeria", callingCode: "213", code: "DZ", flag: "🇩🇿", language: 'Ingles' },
  { name: "American Samoa", callingCode: "1684", code: "AS", flag: "🇦🇸", language: 'Ingles' },
  { name: "Andorra", callingCode: "376", code: "AD", flag: "🇦🇩", language: 'Ingles' },
  { name: "Angola", callingCode: "244", code: "AO", flag: "🇦🇴", language: 'Ingles' },
  { name: "Anguilla", callingCode: "1264", code: "AI", flag: "🇦🇮", language: 'Ingles' },
  { name: "Antarctica", callingCode: "672", code: "AQ", flag: "🇦🇶", language: 'Ingles' },
  { name: "Antigua and Barbuda", callingCode: "1268", code: "AG", flag: "🇦🇬", language: 'Ingles' },
  { name: "Argentina", callingCode: "54", code: "AR", flag: "🇦🇷", language: 'Español' },
  { name: "Armenia", callingCode: "374", code: "AM", flag: "🇦🇲", language: 'Ingles' },
  { name: "Aruba", callingCode: "297", code: "AW", flag: "🇦🇼", language: 'Ingles' },
  { name: "Australia", callingCode: "61", code: "AU", flag: "🇦🇺", language: 'Ingles' },
  { name: "Austria", callingCode: "43", code: "AT", flag: "🇦🇹", language: 'Ingles' },
  { name: "Azerbaijan", callingCode: "994", code: "AZ", flag: "🇦🇿", language: 'Ingles' },
  { name: "Bahamas", callingCode: "1242", code: "BS", flag: "🇧🇸", language: 'Ingles' },
  { name: "Bahrain", callingCode: "973", code: "BH", flag: "🇧🇭", language: 'Ingles' },
  { name: "Bangladesh", callingCode: "880", code: "BD", flag: "🇧🇩", language: 'Ingles' },
  { name: "Barbados", callingCode: "1246", code: "BB", flag: "🇧🇧", language: 'Ingles' },
  { name: "Belarus", callingCode: "375", code: "BY", flag: "🇧🇾", language: 'Ingles' },
  { name: "Belgium", callingCode: "32", code: "BE", flag: "🇧🇪", language: 'Ingles' },
  { name: "Belize", callingCode: "501", code: "BZ", flag: "🇧🇿", language: 'Ingles' },
  { name: "Benin", callingCode: "229", code: "BJ", flag: "🇧🇯", language: 'Ingles' },
  { name: "Bermuda", callingCode: "1441", code: "BM", flag: "🇧🇲", language: 'Ingles' },
  { name: "Bhutan", callingCode: "975", code: "BT", flag: "🇧🇹", language: 'Ingles' },
  { name: "Bolivia", callingCode: "591", code: "BO", flag: "🇧🇴", language: 'Español' },
  { name: "Bosnia and Herzegovina", callingCode: "387", code: "BA", flag: "🇧🇦", language: 'Ingles' },
  { name: "Botswana", callingCode: "267", code: "BW", flag: "🇧🇼", language: 'Ingles' },
  { name: "Bouvet Island", callingCode: "47", code: "BV", flag: "🏳", language: 'Ingles' },
  { name: "Brazil", callingCode: "55", code: "BR", flag: "🇧🇷", language: 'Portugués' },
  { name: "British Indian Ocean Territory", callingCode: "246", code: "IO", flag: "🇮🇴", language: 'Ingles' },
  { name: "Brunei Darussalam", callingCode: "673", code: "BN", flag: "🇧🇳", language: 'Ingles' },
  { name: "Bulgaria", callingCode: "359", code: "BG", flag: "🇧🇬", language: 'Ingles' },
  { name: "Burkina Faso", callingCode: "226", code: "BF", flag: "🇧🇫", language: 'Ingles' },
  { name: "Burundi", callingCode: "257", code: "BI", flag: "🇧🇮", language: 'Ingles' },
  { name: "Cambodia", callingCode: "855", code: "KH", flag: "🇰🇭", language: 'Ingles' },
  { name: "Cameroon", callingCode: "237", code: "CM", flag: "🇨🇲", language: 'Ingles' },
  { name: "Canada", callingCode: "1", code: "CA", flag: "🇨🇦", language: 'Ingles' },
  { name: "Cape Verde", callingCode: "238", code: "CV", flag: "🇨🇻", language: 'Ingles' },
  { name: "Cayman Islands", callingCode: " 345", code: "KY", flag: "🇰🇾", language: 'Ingles' },
  { name: "Central African Republic", callingCode: "236", code: "CF", flag: "🇨🇫", language: 'Ingles' },
  { name: "Chad", callingCode: "235", code: "TD", flag: "🇹🇩", language: 'Ingles' },
  { name: "Chile", callingCode: "56", code: "CL", flag: "🇨🇱", language: 'Español' },
  { name: "China", callingCode: "86", code: "CN", flag: "🇨🇳", language: 'Ingles' },
  { name: "Christmas Island", callingCode: "61", code: "CX", flag: "🇨🇽", language: 'Ingles' },
  { name: "Cocos (Keeling) Islands", callingCode: "61", code: "CC", flag: "🇨🇨", language: 'Ingles' },
  { name: "Colombia", callingCode: "57", code: "CO", flag: "🇨🇴", language: 'Español' },
  { name: "Comoros", callingCode: "269", code: "KM", flag: "🇰🇲", language: 'Ingles' },
  { name: "Congo", callingCode: "242", code: "CG", flag: "🇨🇬", language: 'Ingles' },
  { name: "Congo, The Democratic Republic of the Congo", callingCode: "243", code: "CD", flag: "🇨🇩", language: 'Ingles' },
  { name: "Cook Islands", callingCode: "682", code: "CK", flag: "🇨🇰", language: 'Ingles' },
  { name: "Costa Rica", callingCode: "506", code: "CR", flag: "🇨🇷", language: 'Español' },
  { name: "Cote d'Ivoire", callingCode: "225", code: "CI", flag: "🇨🇮", language: 'Ingles' },
  { name: "Croatia", callingCode: "385", code: "HR", flag: "🇭🇷", language: 'Ingles' },
  { name: "Cuba", callingCode: "53", code: "CU", flag: "🇨🇺", language: 'Ingles' },
  { name: "Cyprus", callingCode: "357", code: "CY", flag: "🇨🇾", language: 'Ingles' },
  { name: "Czech Republic", callingCode: "420", code: "CZ", flag: "🇨🇿", language: 'Ingles' },
  { name: "Denmark", callingCode: "45", code: "DK", flag: "🇩🇰", language: 'Ingles' },
  { name: "Djibouti", callingCode: "253", code: "DJ", flag: "🇩🇯", language: 'Ingles' },
  { name: "Dominica", callingCode: "1767", code: "DM", flag: "🇩🇲", language: 'Ingles' },
  { name: "Dominican Republic", callingCode: "1849", code: "DO", flag: "🇨🇩", language: 'Ingles' },
  { name: "Ecuador", callingCode: "593", code: "EC", flag: "🇪🇨", language: 'Español' },
  { name: "Egypt", callingCode: "20", code: "EG", flag: "🇪🇬", language: 'Ingles' },
  { name: "El Salvador", callingCode: "503", code: "SV", flag: "🇸🇻", language: 'España' },
  { name: "Equatorial Guinea", callingCode: "240", code: "GQ", flag: "🇬🇶", language: 'Ingles' },
  { name: "Eritrea", callingCode: "291", code: "ER", flag: "🇪🇷", language: 'Ingles' },
  { name: "Estonia", callingCode: "372", code: "EE", flag: "🇪🇪", language: 'Ingles' },
  { name: "Ethiopia", callingCode: "251", code: "ET", flag: "🇪🇹", language: 'Ingles' },
  { name: "Falkland Islands (Malvinas)", callingCode: "500", code: "FK", flag: "🇫🇰", language: 'Ingles' },
  { name: "Faroe Islands", callingCode: "298", code: "FO", flag: "🇫🇴", language: 'Ingles' },
  { name: "Fiji", callingCode: "679", code: "FJ", flag: "🇫🇯", language: 'Ingles' },
  { name: "Finland", callingCode: "358", code: "FI", flag: "🇫🇮", language: 'Ingles' },
  { name: "France", callingCode: "33", code: "FR", flag: "🇫🇷", language: 'Ingles' },
  { name: "French Guiana", callingCode: "594", code: "GF", flag: "🇬🇫", language: 'Ingles' },
  { name: "French Polynesia", callingCode: "689", code: "PF", flag: "🇵🇫", language: 'Ingles' },
  { name: "French Southern Territories", callingCode: "262", code: "TF", flag: "🇹🇫", language: 'Ingles' },
  { name: "Gabon", callingCode: "241", code: "GA", flag: "🇬🇦", language: 'Ingles' },
  { name: "Gambia", callingCode: "220", code: "GM", flag: "🇬🇲", language: 'Ingles' },
  { name: "Georgia", callingCode: "995", code: "GE", flag: "🇬🇪", language: 'Ingles' },
  { name: "Germany", callingCode: "49", code: "DE", flag: "🇩🇪", language: 'Ingles' },
  { name: "Ghana", callingCode: "233", code: "GH", flag: "🇬🇭", language: 'Ingles' },
  { name: "Gibraltar", callingCode: "350", code: "GI", flag: "🇬🇮", language: 'Ingles' },
  { name: "Greece", callingCode: "30", code: "GR", flag: "🇬🇷", language: 'Ingles' },
  { name: "Greenland", callingCode: "299", code: "GL", flag: "🇬🇱", language: 'Ingles' },
  { name: "Grenada", callingCode: "1473", code: "GD", flag: "🇬🇩", language: 'Ingles' },
  { name: "Guadeloupe", callingCode: "590", code: "GP", flag: "🇬🇵", language: 'Ingles' },
  { name: "Guam", callingCode: "1671", code: "GU", flag: "🇬🇺", language: 'Ingles' },
  { name: "Guatemala", callingCode: "502", code: "GT", flag: "🇬🇹", language: 'Español' },
  { name: "Guernsey", callingCode: "44", code: "GG", flag: "🇬🇬", language: 'Ingles' },
  { name: "Guinea", callingCode: "224", code: "GN", flag: "🇬🇳", language: 'Ingles' },
  { name: "Guinea-Bissau", callingCode: "245", code: "GW", flag: "🇬🇼", language: 'Ingles' },
  { name: "Guyana", callingCode: "592", code: "GY", flag: "🇬🇾", language: 'Ingles' },
  { name: "Haiti", callingCode: "509", code: "HT", flag: "🇭🇹", language: 'Ingles' },
  { name: "Heard Island and Mcdonald Islands", callingCode: "0", code: "HM", flag: "🏳", language: 'Ingles' },
  { name: "Holy See (Vatican City State)", callingCode: "379", code: "VA", flag: "🇻🇦", language: 'Ingles' },
  { name: "Honduras", callingCode: "504", code: "HN", flag: "🇭🇳", language: 'Español' },
  { name: "Hong Kong", callingCode: "852", code: "HK", flag: "🇭🇰", language: 'Ingles' },
  { name: "Hungary", callingCode: "36", code: "HU", flag: "🇭🇺", language: 'Ingles' },
  { name: "Iceland", callingCode: "354", code: "IS", flag: "🇮🇸", language: 'Ingles' },
  { name: "India", callingCode: "91", code: "IN", flag: "🇮🇳", language: 'Ingles' },
  { name: "Indonesia", callingCode: "62", code: "ID", flag: "🇮🇩", language: 'Ingles' },
  { name: "Iran, Islamic Republic of Persian Gulf", callingCode: "98", code: "IR", flag: "🇮🇷", language: 'Ingles' },
  { name: "Iraq", callingCode: "964", code: "IQ", flag: "🇮🇶", language: 'Ingles' },
  { name: "Ireland", callingCode: "353", code: "IE", flag: "🇮🇪", language: 'Ingles' },
  { name: "Isle of Man", callingCode: "44", code: "IM", flag: "🇮🇲", language: 'Ingles' },
  { name: "Israel", callingCode: "972", code: "IL", flag: "🇮🇱", language: 'Ingles' },
  { name: "Italy", callingCode: "39", code: "IT", flag: "🇮🇹", language: 'Ingles' },
  { name: "Jamaica", callingCode: "1876", code: "JM", flag: "🇯🇲", language: 'Ingles' },
  { name: "Japan", callingCode: "81", code: "JP", flag: "🇯🇵", language: 'Ingles' },
  { name: "Jersey", callingCode: "44", code: "JE", flag: "🇯🇪", language: 'Ingles' },
  { name: "Jordan", callingCode: "962", code: "JO", flag: "🇯🇴", language: 'Ingles' },
  { name: "Kazakhstan", callingCode: "7", code: "KZ", flag: "🇰🇿", language: 'Ingles' },
  { name: "Kenya", callingCode: "254", code: "KE", flag: "🇰🇪", language: 'Ingles' },
  { name: "Kiribati", callingCode: "686", code: "KI", flag: "🇰🇮", language: 'Ingles' },
  { name: "Korea, Democratic People's Republic of Korea", callingCode: "850", code: "KP", flag: "🇰🇵", language: 'Ingles' },
  { name: "Korea, Republic of South Korea", callingCode: "82", code: "KR", flag: "🇰🇷", language: 'Ingles' },
  { name: "Kosovo", callingCode: "383", code: "XK", flag: "🇽🇰", language: 'Ingles' },
  { name: "Kuwait", callingCode: "965", code: "KW", flag: "🇰🇼", language: 'Ingles' },
  { name: "Kyrgyzstan", callingCode: "996", code: "KG", flag: "🇰🇬", language: 'Ingles' },
  { name: "Laos", callingCode: "856", code: "LA", flag: "🇱🇦", language: 'Ingles' },
  { name: "Latvia", callingCode: "371", code: "LV", flag: "🇱🇻", language: 'Ingles' },
  { name: "Lebanon", callingCode: "961", code: "LB", flag: "🇱🇧", language: 'Ingles' },
  { name: "Lesotho", callingCode: "266", code: "LS", flag: "🇱🇸", language: 'Ingles' },
  { name: "Liberia", callingCode: "231", code: "LR", flag: "🇱🇷", language: 'Ingles' },
  { name: "Libyan Arab Jamahiriya", callingCode: "218", code: "LY", flag: "🇱🇾", language: 'Ingles' },
  { name: "Liechtenstein", callingCode: "423", code: "LI", flag: "🇱🇮", language: 'Ingles' },
  { name: "Lithuania", callingCode: "370", code: "LT", flag: "🇱🇹", language: 'Ingles' },
  { name: "Luxembourg", callingCode: "352", code: "LU", flag: "🇱🇺", language: 'Ingles' },
  { name: "Macao", callingCode: "853", code: "MO", flag: "🇲🇴", language: 'Ingles' },
  { name: "Macedonia", callingCode: "389", code: "MK", flag: "🇲🇰", language: 'Ingles' },
  { name: "Madagascar", callingCode: "261", code: "MG", flag: "🇲🇬", language: 'Ingles' },
  { name: "Malawi", callingCode: "265", code: "MW", flag: "🇲🇼", language: 'Ingles' },
  { name: "Malaysia", callingCode: "60", code: "MY", flag: "🇲🇾", language: 'Ingles' },
  { name: "Maldives", callingCode: "960", code: "MV", flag: "🇲🇻", language: 'Ingles' },
  { name: "Mali", callingCode: "223", code: "ML", flag: "🇲🇱", language: 'Ingles' },
  { name: "Malta", callingCode: "356", code: "MT", flag: "🇲🇹", language: 'Ingles' },
  { name: "Marshall Islands", callingCode: "692", code: "MH", flag: "🇲🇭", language: 'Ingles' },
  { name: "Martinique", callingCode: "596", code: "MQ", flag: "🇲🇶", language: 'Ingles' },
  { name: "Mauritania", callingCode: "222", code: "MR", flag: "🇲🇷", language: 'Ingles' },
  { name: "Mauritius", callingCode: "230", code: "MU", flag: "🇲🇺", language: 'Ingles' },
  { name: "Mayotte", callingCode: "262", code: "YT", flag: "🇾🇹", language: 'Ingles' },
  { name: "Mexico", callingCode: "52", code: "MX", flag: "🇲🇽", language: 'Español' },
  { name: "Micronesia, Federated States of Micronesia", callingCode: "691", code: "FM", flag: "🇫🇲", language: 'Ingles' },
  { name: "Moldova", callingCode: "373", code: "MD", flag: "🇲🇩", language: 'Ingles' },
  { name: "Monaco", callingCode: "377", code: "MC", flag: "🇲🇨", language: 'Ingles' },
  { name: "Mongolia", callingCode: "976", code: "MN", flag: "🇲🇳", language: 'Ingles' },
  { name: "Montenegro", callingCode: "382", code: "ME", flag: "🇲🇪", language: 'Ingles' },
  { name: "Montserrat", callingCode: "1664", code: "MS", flag: "🇲🇸", language: 'Ingles' },
  { name: "Morocco", callingCode: "212", code: "MA", flag: "🇲🇦", language: 'Ingles' },
  { name: "Mozambique", callingCode: "258", code: "MZ", flag: "🇲🇿", language: 'Ingles' },
  { name: "Myanmar", callingCode: "95", code: "MM", flag: "🇲🇲", language: 'Ingles' },
  { name: "Namibia", callingCode: "264", code: "NA", flag: "🇳🇦", language: 'Ingles' },
  { name: "Nauru", callingCode: "674", code: "NR", flag: "🇳🇷", language: 'Ingles' },
  { name: "Nepal", callingCode: "977", code: "NP", flag: "🇳🇵", language: 'Ingles' },
  { name: "Netherlands", callingCode: "31", code: "NL", flag: "🇳🇱", language: 'Ingles' },
  { name: "Netherlands Antilles", callingCode: "599", code: "AN", flag: "🇳🇱", language: 'Ingles' },
  { name: "New Caledonia", callingCode: "687", code: "NC", flag: "🇳🇨", language: 'Ingles' },
  { name: "New Zealand", callingCode: "64", code: "NZ", flag: "🇳🇿", language: 'Ingles' },
  { name: "Nicaragua", callingCode: "505", code: "NI", flag: "🇳🇮", language: 'Ingles' },
  { name: "Niger", callingCode: "227", code: "NE", flag: "🇳🇪", language: 'Ingles' },
  { name: "Nigeria", callingCode: "234", code: "NG", flag: "🇳🇬", language: 'Ingles' },
  { name: "Niue", callingCode: "683", code: "NU", flag: "🇳🇺", language: 'Ingles' },
  { name: "Norfolk Island", callingCode: "672", code: "NF", flag: "🇳🇫", language: 'Ingles' },
  { name: "Northern Mariana Islands", callingCode: "1670", code: "MP", flag: "🏳", language: 'Ingles' },
  { name: "Norway", callingCode: "47", code: "NO", flag: "🇳🇴", language: 'Ingles' },
  { name: "Oman", callingCode: "968", code: "OM", flag: "🇴🇲", language: 'Ingles' },
  { name: "Pakistan", callingCode: "92", code: "PK", flag: "🇵🇰", language: 'Ingles' },
  { name: "Palau", callingCode: "680", code: "PW", flag: "🇵🇼", language: 'Ingles' },
  { name: "Palestinian Territory, Occupied", callingCode: "970", code: "PS", flag: "🇵🇸", language: 'Ingles' },
  { name: "Panama", callingCode: "507", code: "PA", flag: "🇵🇦", language: 'Español' },
  { name: "Papua New Guinea", callingCode: "675", code: "PG", flag: "🇵🇬", language: 'Ingles' },
  { name: "Paraguay", callingCode: "595", code: "PY", flag: "🇵🇾", language: 'Español' },
  { name: "Peru", callingCode: "51", code: "PE", flag: "🇵🇪", language: 'Español' },
  { name: "Philippines", callingCode: "63", code: "PH", flag: "🇵🇭", language: 'Ingles' },
  { name: "Pitcairn", callingCode: "64", code: "PN", flag: "🇵🇳", language: 'Ingles' },
  { name: "Poland", callingCode: "48", code: "PL", flag: "🇵🇱", language: 'Ingles' },
  { name: "Portugal", callingCode: "351", code: "PT", flag: "🇵🇹", language: 'Ingles' },
  { name: "Puerto Rico", callingCode: "1939", code: "PR", flag: "🇵🇷", language: 'Ingles' },
  { name: "Qatar", callingCode: "974", code: "QA", flag: "🇶🇦", language: 'Ingles' },
  { name: "Romania", callingCode: "40", code: "RO", flag: "🇷🇴", language: 'Ingles' },
  { name: "Russia", callingCode: "7", code: "RU", flag: "🇷🇺", language: 'Ingles' },
  { name: "Rwanda", callingCode: "250", code: "RW", flag: "🇷🇼", language: 'Ingles' },
  { name: "Reunion", callingCode: "262", code: "RE", flag: "🇫🇷", language: 'Ingles' },
  { name: "Saint Barthelemy", callingCode: "590", code: "BL", flag: "🇧🇱", language: 'Ingles' },
  { name: "Saint Helena, Ascension and Tristan Da Cunha", callingCode: "290", code: "SH", flag: "🇸🇭", language: 'Ingles' },
  { name: "Saint Kitts and Nevis", callingCode: "1869", code: "KN", flag: "🇰🇳", language: 'Ingles' },
  { name: "Saint Lucia", callingCode: "1758", code: "LC", flag: "🇱🇨", language: 'Ingles' },
  { name: "Saint Martin", callingCode: "590", code: "MF", flag: "🏳", language: 'Ingles' },
  { name: "Saint Pierre and Miquelon", callingCode: "508", code: "PM", flag: "🇵🇲", language: 'Ingles' },
  { name: "Saint Vincent and the Grenadines", callingCode: "1784", code: "VC", flag: "🇻🇨", language: 'Ingles' },
  { name: "Samoa", callingCode: "685", code: "WS", flag: "🇼🇸", language: 'Ingles' },
  { name: "San Marino", callingCode: "378", code: "SM", flag: "🇸🇲", language: 'Ingles' },
  { name: "Sao Tome and Principe", callingCode: "239", code: "ST", flag: "🇸🇹", language: 'Ingles' },
  { name: "Saudi Arabia", callingCode: "966", code: "SA", flag: "🇸🇦", language: 'Ingles' },
  { name: "Senegal", callingCode: "221", code: "SN", flag: "🇸🇳", language: 'Ingles' },
  { name: "Serbia", callingCode: "381", code: "RS", flag: "🇷🇸", language: 'Ingles' },
  { name: "Seychelles", callingCode: "248", code: "SC", flag: "🇸🇨", language: 'Ingles' },
  { name: "Sierra Leone", callingCode: "232", code: "SL", flag: "🇸🇱", language: 'Ingles' },
  { name: "Singapore", callingCode: "65", code: "SG", flag: "🇸🇬", language: 'Ingles' },
  { name: "Slovakia", callingCode: "421", code: "SK", flag: "🇸🇰", language: 'Ingles' },
  { name: "Slovenia", callingCode: "386", code: "SI", flag: "🇸🇮", language: 'Ingles' },
  { name: "Solomon Islands", callingCode: "677", code: "SB", flag: "🇸🇧", language: 'Ingles' },
  { name: "Somalia", callingCode: "252", code: "SO", flag: "🇸🇴", language: 'Ingles' },
  { name: "South Africa", callingCode: "27", code: "ZA", flag: "🇿🇦", language: 'Ingles' },
  { name: "South Sudan", callingCode: "211", code: "SS", flag: "🇸🇸", language: 'Ingles' },
  { name: "South Georgia and the South Sandwich Islands", callingCode: "500", code: "GS", flag: "🇬🇸", language: 'Ingles' },
  { name: "Spain", callingCode: "34", code: "ES", flag: "🇪🇸", language: 'Español' },
  { name: "Sri Lanka", callingCode: "94", code: "LK", flag: "🇱🇰", language: 'Ingles' },
  { name: "Sudan", callingCode: "249", code: "SD", flag: "🇸🇩", language: 'Ingles' },
  { name: "Suriname", callingCode: "597", code: "SR", flag: "🇸🇷", language: 'Ingles' },
  { name: "Svalbard and Jan Mayen", callingCode: "47", code: "SJ", flag: "🇩🇰", language: 'Ingles' },
  { name: "Swaziland", callingCode: "268", code: "SZ", flag: "🇸🇿", language: 'Ingles' },
  { name: "Sweden", callingCode: "46", code: "SE", flag: "🇸🇪", language: 'Ingles' },
  { name: "Switzerland", callingCode: "41", code: "CH", flag: "🇨🇭", language: 'Ingles' },
  { name: "Syrian Arab Republic", callingCode: "963", code: "SY", flag: "🇸🇾", language: 'Ingles' },
  { name: "Taiwan", callingCode: "886", code: "TW", flag: "🇹🇼", language: 'Ingles' },
  { name: "Tajikistan", callingCode: "992", code: "TJ", flag: "🇹🇯", language: 'Ingles' },
  { name: "Tanzania, United Republic of Tanzania", callingCode: "255", code: "TZ", flag: "🇹🇿", language: 'Ingles' },
  { name: "Thailand", callingCode: "66", code: "TH", flag: "🇹🇭", language: 'Ingles' },
  { name: "Timor-Leste", callingCode: "670", code: "TL", flag: "🇹🇱", language: 'Ingles' },
  { name: "Togo", callingCode: "228", code: "TG", flag: "🇹🇬", language: 'Ingles' },
  { name: "Tokelau", callingCode: "690", code: "TK", flag: "🇹🇰", language: 'Ingles' },
  { name: "Tonga", callingCode: "676", code: "TO", flag: "🇹🇴", language: 'Ingles' },
  { name: "Trinidad and Tobago", callingCode: "1868", code: "TT", flag: "🇹🇹", language: 'Ingles' },
  { name: "Tunisia", callingCode: "216", code: "TN", flag: "🇹🇳", language: 'Ingles' },
  { name: "Turkey", callingCode: "90", code: "TR", flag: "🇹🇷", language: 'Ingles' },
  { name: "Turkmenistan", callingCode: "993", code: "TM", flag: "🇹🇲", language: 'Ingles' },
  { name: "Turks and Caicos Islands", callingCode: "1649", code: "TC", flag: "🇹🇨", language: 'Ingles' },
  { name: "Tuvalu", callingCode: "688", code: "TV", flag: "🇹🇻", language: 'Ingles' },
  { name: "Uganda", callingCode: "256", code: "UG", flag: "🇺🇬", language: 'Ingles' },
  { name: "Ukraine", callingCode: "380", code: "UA", flag: "🇺🇦", language: 'Ingles' },
  { name: "United Arab Emirates", callingCode: "971", code: "AE", flag: "🇦🇪", language: 'Ingles' },
  { name: "United Kingdom", callingCode: "44", code: "GB", flag: "🇬🇧", language: 'Ingles' },
  { name: "United States", callingCode: "1", code: "US", flag: "🇺🇸", language: 'Ingles' },
  { name: "Uruguay", callingCode: "598", code: "UY", flag: "🇺🇾", language: 'Español' },
  { name: "Uzbekistan", callingCode: "998", code: "UZ", flag: "🇺🇿", language: 'Ingles' },
  { name: "Vanuatu", callingCode: "678", code: "VU", flag: "🇻🇺", language: 'Ingles' },
  { name: "Venezuela", callingCode: "58", code: "VE", flag: "🇻🇪", language: 'Español' },
  { name: "Vietnam", callingCode: "84", code: "VN", flag: "🇻🇳", language: 'Ingles' },
  { name: "Virgin Islands, British", callingCode: "1284", code: "VG", flag: "🇻🇬", language: 'Ingles' },
  { name: "Virgin Islands, U.S.", callingCode: "1340", code: "VI", flag: "🇻🇮", language: 'Ingles' },
  { name: "Wallis and Futuna", callingCode: "681", code: "WF", flag: "🇼🇫", language: 'Ingles' },
  { name: "Yemen", callingCode: "967", code: "YE", flag: "🇾🇪", language: 'Ingles' },
  { name: "Zambia", callingCode: "260", code: "ZM", flag: "🇿🇲", language: 'Ingles' },
  { name: "Zimbabwe", callingCode: "263", code: "ZW", flag: "🇿🇼", language: 'Ingles' },
];

module.exports = {
  countriesData: countriesData
} 